version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server-container
    ports:
      - "443:443"
    networks:
      - tls-network

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: client-container
    volumes:
      - shared:/shared
    depends_on:
      - server
    networks:
      - tls-network

volumes:
  shared:

networks:
  tls-network:
    driver: bridge