version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
      network: host
    container_name: server-container
    ports:
      - "443:443"
    networks:
      - tls-net

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
      network: host
    container_name: client-container
    volumes:
      - shared:/shared
    depends_on:
      - server
    networks:
      - tls-net

volumes:
  shared:

networks:
  tls-network:
    driver: bridge