FROM ubuntu:latest

RUN apt update && apt install -y nginx openssl easy-rsa

RUN mkdir -p /etc/nginx/ca /etc/nginx/certs /shared

RUN echo "<html><head><title>TLS Project Test Page</title></head>\
<body><h1>TLS Project Test Page</h1>\
<p>This page is served over TLS 1.3 with ECC certificates.</p></body></html>" > /var/www/html/index.html

EXPOSE 80 443

CMD ["nginx", "-g", "daemon off;"]