version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
      network: host
    container_name: server-container
    ports:
      - "443:443"
    networks:
      tls-net:
        ipv4_address: 172.20.0.2

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
      network: host
    container_name: client-container
    volumes:
      - shared:/shared
    depends_on:
      - server
    networks:
      tls-net:
        ipv4_address: 172.20.0.3

volumes:
  shared:

networks:
  tls-net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16