version: '3'
services:
  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: server-container
    networks:
      custom:
        ipv4_address: 172.20.0.2
    volumes:
      - shared:/shared

  client:
    build:
      context: .
      dockerfile: Dockerfile.client
    container_name: client-container
    networks:
      custom:
        ipv4_address: 172.20.0.3
    volumes:
      - shared:/shared
    depends_on:
      - server

networks:
  custom:
    name: custom
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

volumes:
  shared: