name: TLS Testing
on: [push, pull_request]

jobs:
 test:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     
     - name: Install Docker Compose
       run: sudo apt-get install -y docker-compose
     
     - name: Build and Start Containers
       run: |
         docker compose build --no-cache
         docker compose up -d
     
     - name: Install DNS Tools
       run: |
         docker exec client-container apt-get update
         docker exec client-container apt-get install -y dnsutils iputils-ping net-tools
         
     - name: Basic Container Test
       run: |
         docker compose up -d
         docker ps
         docker network ls
         docker inspect client-container | grep IPAddress
         docker inspect server-container | grep IPAddress
     
     - name: Debug Network
       run: |
         docker network ls
         docker network inspect team15-project5-test_default
         docker exec client-container cat /etc/hosts
         docker inspect server-container | grep IPAddress
         docker exec client-container ping -c 2 server-container
         
     - name: Check Shared Volume
       run: |
         docker exec client-container ls -la /shared/
         docker exec server-container ls -la /shared/
         
     - name: Test TLS Setup
       run: |
         docker exec client-container curl -v --cert /shared/client.crt \
           --key /shared/client.key -k https://server-container:443
     
     - name: Capture TLS Traffic
       run: |
         mkdir -p artifacts/pcap
         docker exec client-container tcpdump -i any -w /shared/tls_handshake.pcap &
         sleep 2
         docker exec client-container curl -v --cert /shared/client.crt \
           --key /shared/client.key -k https://server-container
         sleep 2
         docker exec client-container pidof tcpdump | xargs docker exec client-container kill
         docker cp client-container:/shared/tls_handshake.pcap artifacts/pcap/
     
     - name: Upload Artifacts
       uses: actions/upload-artifact@v3
       with:
         name: test-results
         path: artifacts/